site_name: 써드아이시스템(3rdeyesys) 기술문서
site_url: 'https://docs.3rdeyesys.com'
site_description: 클라우드 서버를 비롯한 각종 IT 관련 기술 자료들을 공유하는 써드아이시스템(3rdeyesys)의 기술문서 사이트입니다. 네이버 클라우드(NAVER CLOUD), AWS 등의 클라우드를 이용할 때 중요한 기술문서들을 공유합니다. 써드아이시스템은 네이버클라우드 프리미엄 파트너사입니다.


theme:
  name: material
  language: kr
  custom_dir: overrides  
  features:
    - navigation.sections
  
  palette:
    scheme: default
    primary: green
    favicon: assets/favicon.png

plugins:
    - search
    - awesome-pages
    
markdown_extensions:
    - smarty
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.critic

extra_javascript:
  - javascripts/extra.js
    
edit_uri: docs/docs
